version: "3.4"
services:
 vite_docker:
   image: node:lts-alpine
   container_name: bora_pagar_front
   entrypoint: /bin/sh -c "corepack enable && yarn set version stable && sh"
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
