spring:
    data:
        mongodb:
            uri: ${DATABASE_URI}
            database: ${DATABASE_NAME}
    config:
        import: optional:secrets.yml
    jackson:
        mapper:
            default-view-inclusion: true